### ISSUE TITLE
Missing Collection Log Entries (Callisto, Venenatis, and Vet'ion)

### ISSUE THREAD

**Issue by ThirdStockIII** [evansloan/collectionlog.net#32]
I just installed the plugin but the data isn't appearing on collectionlog.net yet. I think the issue is plugin is requiring the entries for Callisto, Venenatis, and Vet'ion but the game has changed those collection log tabs to include their lower leveled variants. Before installing the plugin, my account name would just say account not found or whatever and now it is a blank screen, so something has definitely changed since I installed the plugin. I also tried logging out and back in a couple of times, so the last thing I can think of is the fact that I am not able to click on the old pages of Callisto, Venenatis, and Vet'ion.

**Comment by evansloan** [comment]
What is your username?

**Comment by ThirdStockIII** [comment]
My username is 3rdStockIII. Here is a screenshot of what the plugin tab
says is missing in case it helps resolve the issue.

**Comment by evansloan** [comment]
Thanks for the info. Seems like the only tab you had uploaded to the site was the "Other" tab. Not sure how that happened, since the plugin says you clicked through all the other pages/tabs. Could have timed out during the upload process and failed to properly update, which I think is the cause due to your log being stuck in an updating state on the site.

When you have the chance open your log in-game twice and try to upload again. There's a bug in the plugin right now that has a fix under review that prevents the unique item counts from updating without opening the log twice.

**Comment by ThirdStockIII** [comment]
I clicked through all the tabs in the collection log again and my data is now populating on the website. Thank you so much for the help and for the time spent developing this tool.

**Comment by evansloan** [comment]
Glad to hear. Sorry for the inconveniences.
